version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5433:5432"   # <--- IMPORTANT: Host 5433 â†’ Container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: library-backend
    restart: always
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/library"
      JWT_SECRET: "supersecret123"
      JWT_EXPIRES_IN: "1d"
      PORT: 3333
    depends_on:
      - db

volumes:
  pgdata:
